# Basic Codemagic YAML configuration for an Android (Java/Gradle) project

workflows:
  android-debug-build:
    name: "Android Debug Build"
    instance_type: mac_mini_m2 # Using macOS M2 instance

    environment:
      java: 11 # Changed from 17 to 11 for compatibility with Gradle 6.1.1

    cache: # Optional: Caching Gradle dependencies
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper # Cache Gradle wrapper downloads

    triggering: # Basic trigger: run on push to any branch
      events:
        - push
      branch_patterns:
        - pattern: '*' # Match all branches
          include: true

    scripts:
      - name: "Set execute permissions for gradlew"
        script: |
          chmod +x ./gradlew
      - name: "Stop existing Gradle daemons (if any)"
        script: |
          ./gradlew --stop
      - name: "Clean project"
        script: |
          ./gradlew clean
      - name: "Build debug APK"
        script: |
          ./gradlew :app:assembleDebug # Specify module :app: explicitly

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/** # Collect build reports
      - app/build/test-results/** # Collect test results if any tests were run
